[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = true
evm_version = "paris"
gas_reports = ["*"]

[profile.ci]
fuzz = { runs = 256 }
invariant = { runs = 256 }

